main: dev.amraleth.afo.AfoPlugin
name: Afo
author: Amraleth
description: A complete revamp of Minecraft's vanilla fishing mechanic
version: 1.0-alpha
website: https://github.com/amraleth/afo
api-version: 1.21.5